### ISSUE TITLE
Could you provide a "ignore SSL issues" checkbox

### ISSUE THREAD

**Issue by Bjego** [Cdiscount/vsts-buildtask-marathon#2]
Hey guys,
to use our internal marathon environment. I would like to have an ignore SSL issues flag. Could you provide one, so that I can use your plugin in our inhouse environment?

Thanks in advance.

**Comment by follyadjanoh** [comment]
Hello @Bjego. Do you mean a checkbox allowing requests for invalid ssl certificate ?

**Comment by Bjego** [comment]
Yes I thought so. This could help us here to use our inhouse Marathon environment much easier.

**Comment by follyadjanoh** [comment]
I make new commit for the checkbox (in advanced group). 
Could you create the extension from the new code and test it ? 
Please tell us if it works. So that i can publish this version on the marketplace. I can't test it in our environment. 
Thanks

![2018-03-13_16h34_34](https://user-images.githubusercontent.com/28731068/37352024-9d0453fa-26dc-11e8-84fa-fc2e00b0a58c.png)

**Comment by Bjego** [comment]
Hey, I also started working on it. I die many changes today at Work, but i can' t access GitHub from there. 
I added asnyc and await and moved Thema create requests Options stuff into Thema Options Class. 
Hopefully I can Check my Buffer changes tomorrow and Bring them somehow into GitHub. You can decide Then If want to merge them.
I also want to add a Feature which Checks If the Container ist really running after pushing the config.

**Comment by Bjego** [comment]
Damn my mobile phone corrected the spelling.. going to write the comment again on a PC tomorrow

**Comment by Bjego** [comment]
Hey, I also started working on it. I did many changes today at Work, but i can' t access GitHub from there.
 I added async and await and moved the create requests Options stuff into the Options Class.
Hopefully I can checkin my changes tomorrow and bring them somehow into GitHub. You can decide then if you want to merge them.
 I also want to add a feature which checks that the container is really running after pushing the config.
